name: Update Pre-commit Hooks

on:
  schedule:
    # Run monthly on the 1st at 9 AM UTC
    - cron: '0 9 1 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install pre-commit
        run: uv tool install pre-commit

      - name: Update pre-commit hooks
        run: uv tool run pre-commit autoupdate

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update pre-commit hooks to latest versions"
          title: "🔄 Update pre-commit hooks"
          body: |
            This PR updates the pre-commit hooks to their latest versions.

            **Changes:**
            - Updated pre-commit hook versions automatically
            - Ensures project uses latest security and linting rules

            **Generated by:** GitHub Actions workflow
          branch: update-precommit-hooks
          delete-branch: true
